type class: object {
	var name: string

	function hashCode(): i32 => this as i32

	function ok() { 
		print("ok")
	}
	function toString(): string => name
}

extension class {
	function done {
		print("done")
	}

	property prop: string {
		get {
			return name
		}
		set {
			name = value
			print(name)
		}
	}
}

main {
	var ex = new class()
	var num = 10
	ex.name = "John " + "Doe"
	print(ex.name)
	ex.done()
}